#!/usr/bin/with-contenv bash

if [ ! -f "/app/healthchecks/hc/local_settings.py" ]; then
	ln -s /config/local_settings.py /app/healthchecks/hc/local_settings.py
fi

if [ ! -f "/app/healthchecks/hc.sqlite" ]; then
	touch /data/hc.sqlite
	ln -s /data/hc.sqlite /app/healthchecks/hc.sqlite
fi

if [ ! -d "/config/img" ]; then
	mkdir /config/img
fi

mv /defaults/uwsgi.ini /app/healthchecks/uwsgi.ini > /dev/null 2>&1

# copy over configurable logo files
FILES="favicon.ico
apple-touch-180.png
logo@2x.png
logo.png
logo-512-green.png
logo-full@2x.png
logo-full.png"
for f in $FILES
do
	if [ ! -f "/config/img/$f" ]; then
		cp "/app/healthchecks/static/img/$f" "/config/img/$f"
	fi

	rm "/app/healthchecks/static/img/$f" > /dev/null 2>&1
	ln -s "/config/img/$f" "/app/healthchecks/static/img/$f"
done

# permissions
chown -R abc:abc \
	/app/healthchecks \
	/config

cd /app/healthchecks || exit

s6-setuidgid abc /usr/bin/python3 ./manage.py migrate